change announce for obstacle stop
tier4/vehicle_voice_alert_system pull request #87
Opened 2023-11-10 07:57 UTC by JunichiMorimoto

## PR Type

- Improvement

## Related Links
https://tier4.atlassian.net/browse/RT4-7570

## Description

- use temporary_stop.wav for obstacle stop
- change function name: not_timeout to in_interval
- use constant for MotionState

## Review Procedure

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write release notes

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

2023-11-10 08:00 UTC, JunichiMorimoto commented on src/vehicle_voice_alert_system/src/vehicle_voice_alert_system/announce_controller.py
> +    def in_interval(self, timeout_attr):
not_timeoutがしっくり来なかったので in_intervalに変更しています（grep確認済み）

2023-11-10 08:00 UTC, JunichiMorimoto commented on src/vehicle_voice_alert_system/src/vehicle_voice_alert_system/announce_controller.py
> +        self._prev_motion_state = MotionState.UNKNOWN
motion_stateをハードコードしていた部分を MotionStateから取るようにしています

2023-11-10 08:10 UTC, yabuta requested changes

2023-11-10 08:10 UTC, yabuta commented on src/vehicle_voice_alert_system/src/vehicle_voice_alert_system/announce_controller.py
>                  and self._autoware.information.velocity == 0
個々の停止した判定をmotion state==STOPにしたほうがいいかと思います

2023-11-10 08:16 UTC, JunichiMorimoto commented on src/vehicle_voice_alert_system/src/vehicle_voice_alert_system/announce_controller.py
>                  and self._autoware.information.velocity == 0
対応しました！

2023-11-13 01:24 UTC, yabuta commented on src/vehicle_voice_alert_system/src/vehicle_voice_alert_system/announce_controller.py
> +                    "BlindSpot",
多分個々の理由も発話する理由を見直してもらうと思うのですがそれはもう一つのタスクの方でやりたいと思います
Avoidance増やしてほしいとか

2023-11-13 01:24 UTC, yabuta approved these changes
LGTM

2023-11-13 06:23 UTC, tkhmy approved these changes
LGTM

2023-11-17 01:46 UTC, merged