use velocity_factor for the condition of stopping announce
tier4/vehicle_voice_alert_system pull request #88
Opened 2023-12-18 02:29 UTC by JunichiMorimoto

## PR Type

- Improvement

## Related Links

https://tier4.atlassian.net/browse/RT4-7571

## Description

use velocity_factor for the condition of stopping announce

## Review Procedure

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write release notes

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

2023-12-26 00:29 UTC, tkhmy approved these changes
LGTM

2023-12-27 06:38 UTC, yabuta requested changes

2023-12-27 06:38 UTC, yabuta commented on src/vehicle_voice_alert_system/src/vehicle_voice_alert_system/announce_controller.py
> +            self._node.get_logger().warning(
この辺のwarning logは開発用ですかね？
それなら消したほうが良さそうかと

2023-12-28 05:42 UTC, JunichiMorimoto commented on src/vehicle_voice_alert_system/src/vehicle_voice_alert_system/announce_controller.py
> +            self._node.get_logger().warning(
見逃してました、ありがとうございます
削除しました！

2024-01-09 00:28 UTC, yabuta approved these changes
LGTM

2024-01-09 01:42 UTC, merged